name: Update Sam.md

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'iam-sameera'
        repository: 'b'  
    - name: Access cloned repository content
      run: |
        cd b
        sed -i 's/name:abc/name:xyz/g' sam.md
        cat sam.md
            - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        ...
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.PAT }}

            
