name: Update Sam's Name

on:
  push:
    branches:
      - main

jobs:
  update_name:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sam's File
        uses: actions/checkout@v2
        with:
          repository: iam-sameera/b
          path: sam.md

      - name: Verify sam.md file
        run: |
          ls -l sam.md

      - name: Replace name using sed
        run: |
          if [ -f "sam.md" ]; then
            sed -i 's/name: Sameera/name: Dissanayaka/' sam.md
          else
            echo "sam.md file not found"
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add sam.md
          git commit -m "Update Sam's name to Dissanayaka"
          git push
