name: Update Sam's Name

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Repo B
      uses: actions/checkout@v2
      with:
        repository: iam-sameera/b  # Repository B

    - name: Update Sam's Name
      run: |
        sed -i 's/name:Sameera/name:Dissanayaka/g' sam.md

    - name: Commit and Push changes to Repo B
      env:
        PAT: ${{ secrets.PAT }}  # Use the personal access token stored in repository A's secrets
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update Sam's name"
        git remote set-url --push origin https://iam-sameera:$secrets.PAT@github.com/iam-sameera/b
        git push 
        
