name: Update Sam.md

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'iam-sameera'
        repository: 'b'  

    - name: Access cloned repository content
      run: |
        cd b
        sed -i 's/name:abc/name:xyz/g' sam.md
        cat sam.md
        git config --global user.email "devopssameera@gmail.com"
        git config --global user.name "Sameera Dissanayaka"
        git add sam.md
        git commit -m "Update sam.md"

    - name: Push
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ b }}
        git push
