name: Update Sam's Name

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Repo B
      uses: actions/checkout@v2
      with:
        repository: iam-sameera/b  # Repository B

    - name: Update Sam's Name
      run: |
        sed -i 's/name:Sameera/name:Dissanayaka/g' sam.md

    - name: Commit and Push changes to Repo B
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT }}  # Use the personal access token stored in repository A's secrets
      with:
        source-directory: 'b'
        destination-github-username:  'iam-sameera'
        destination-repository-name:  'b'
        user-email: devopssameera@gmail.com
        target-branch: main      
