name: Update Sam.md

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v2
      with:
        repository: iam-sameera/b
        token: ${{ secrets.PAT }}

    - name: Update sam.md
      run: |
        sed -i 's/name:abc/name:xyz/g' sam.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update sam.md"
        git push
